---
- name: Create '{{ software_bin_dir }}' directory
  file:
    path: "{{ software_bin_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0755

- name: Install package 'unzip'
  package:
    name: unzip
    state: present
  when:
    - file_download is match(".+\.zip")

- name: Unarchive '{{ software_tmp_dir }}/{{ file_download }}' to '{{ software_bin_dir }}'
  unarchive:
    src: "{{ software_tmp_dir }}/{{ file_download }}"
    dest: "{{ software_bin_dir }}"
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0750
  when:
    - file_download is match(".+\.zip")

- name: Copy '{{ software_tmp_dir }}/{{ file_download }}' to '{{ software_bin_dir }}/{{ software.name }}'
  copy:
    src: "{{ software_tmp_dir }}/{{ file_download }}"
    dest: "{{ software_bin_dir }}/{{ software.name }}"
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0755
  when:
    - file_download is not match(".+\.zip")

- name:
  file:
    src: "{{ software_bin_dir }}/{{ software.name }}"
    dest: "/usr/bin/{{ software.name }}"
    state: link
    mode: 0755
