---
- name: Create '{{ dir_bin }}' directory
  file:
    path: "{{ dir_bin }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0750

- name: Install package 'unzip'
  package:
    name: unzip
    state: present
  when:
    - file_download is match(".+\.zip")

- name: Unarchive '{{ dir_tmp }}/{{ file_download }}' to '{{ dir_bin }}'
  unarchive:
    src: "{{ dir_tmp }}/{{ file_download }}"
    dest: "{{ dir_bin }}"
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0750
  when:
    - file_download is match(".+\.zip")

- name: Copy '{{ file_download }}' to '{{ dir_bin }}'
  copy:
    src: "{{ dir_tmp }}/{{ file_download }}"
    dest: "{{ dir_bin }}"
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0750
  when:
    - file_download is not match(".+\.zip")